# Generated by Django 2.2.3 on 2019-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('Items', models.CharField(blank=True, choices=[('Ch', 'Chocolate'), ('sp', 'Soap'), ('pw', 'powder')], max_length=30, null=True, verbose_name='Items')),
            ],
        ),
    ]
