# Generated by Django 2.2.3 on 2019-07-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Itemss',
        ),
    ]
