# Generated by Django 2.2.3 on 2019-07-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190702_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, choices=[('EE', 'Electrical'), ('EC', 'Electronics'), ('CS', 'Comp. Science')], max_length=30, null=True, verbose_name='Book name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='Itemss',
        ),
    ]
