# Generated by Django 2.2.3 on 2019-07-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190702_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100, null=True, verbose_name='book')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100, verbose_name='Teacher_name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='library',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='library',
            name='sut',
        ),
        migrations.RemoveField(
            model_name='library',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='library',
            name='libraryname',
            field=models.CharField(max_length=100, null=True, verbose_name='library'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=100, verbose_name='section')),
                ('Students', models.ManyToManyField(to='home.Student')),
                ('advisor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(null=True, to='home.books'),
        ),
    ]
