# Generated by Django 2.2.3 on 2019-07-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190702_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='sut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Student'),
        ),
    ]
