# Generated by Django 2.2.3 on 2019-07-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
